# Generated by Django 6.0 on 2026-01-03 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_materia', models.CharField(max_length=100)),
                ('codigo_materia', models.CharField(max_length=20)),
                ('delegado_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegado_de', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='Eleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_acceso', models.CharField(max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('esta_activa', models.BooleanField(default=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eleccion')),
                ('usuario_candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('usuario_votante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('eleccion', 'usuario_votante')},
            },
        ),
    ]
