# Generated by Django 6.0 on 2026-01-06 04:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elecciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eleccion',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='postulaciones', to=settings.AUTH_USER_MODEL),
        ),
    ]
