# Generated by Django 6.0 on 2026-01-15 02:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrera_options_alter_seccion_options_and_more'),
        ('elecciones', '0002_eleccion_candidatos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleccion',
            options={'verbose_name': 'Elección', 'verbose_name_plural': 'Elecciones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'verbose_name': 'Voto', 'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='candidatos',
            field=models.ManyToManyField(blank=True, related_name='postulaciones', to=settings.AUTH_USER_MODEL, verbose_name='Candidatos'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='esta_activa',
            field=models.BooleanField(default=True, verbose_name='Estado (Activa)'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.materia', verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='eleccion',
            name='token_acceso',
            field=models.CharField(max_length=20, verbose_name='Token de Acceso'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='codigo_materia',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='delegado_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegado_de', to=settings.AUTH_USER_MODEL, verbose_name='Delegado Actual'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='nombre_materia',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Materia'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seccion', verbose_name='Sección'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='eleccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elecciones.eleccion', verbose_name='Elección'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario_candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Candidato votado'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='usuario_votante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_emitidos', to=settings.AUTH_USER_MODEL, verbose_name='Estudiante que votó'),
        ),
    ]
