# Generated by Django 6.0 on 2026-01-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrera',
            options={'verbose_name': 'Carrera', 'verbose_name_plural': 'Carreras'},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={'verbose_name': 'Sección', 'verbose_name_plural': 'Secciones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre_carrera',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Carrera'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='seccion',
            name='codigo_seccion',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código de la Sección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Cédula de Identidad'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='seccion_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.seccion', verbose_name='Sección Base'),
        ),
    ]
